package com.google.adtest;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int alpha = 0x7f010000;
        public static final int font = 0x7f010001;
        public static final int fontProviderAuthority = 0x7f010002;
        public static final int fontProviderCerts = 0x7f010003;
        public static final int fontProviderFetchStrategy = 0x7f010004;
        public static final int fontProviderFetchTimeout = 0x7f010005;
        public static final int fontProviderPackage = 0x7f010006;
        public static final int fontProviderQuery = 0x7f010007;
        public static final int fontProviderSystemFontFamily = 0x7f010008;
        public static final int fontStyle = 0x7f010009;
        public static final int fontVariationSettings = 0x7f01000a;
        public static final int fontWeight = 0x7f01000b;
        public static final int lStar = 0x7f01000c;
        public static final int nestedScrollViewStyle = 0x7f01000d;
        public static final int queryPatterns = 0x7f01000e;
        public static final int shortcutMatchRequired = 0x7f01000f;
        public static final int ttcIndex = 0x7f010010;
    }

    public static final class bool {
        public static final int enable_system_foreground_service_default = 0x7f020001;
        public static final int enable_system_job_service_default = 0x7f020002;
        public static final int workmanager_test_configuration = 0x7f020003;
    }

    public static final class drawable {
        public static final int ic_system_service = 0x7f050006;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f060000;
        public static final int accessibility_custom_action_0 = 0x7f060001;
        public static final int accessibility_custom_action_1 = 0x7f060002;
        public static final int accessibility_custom_action_10 = 0x7f060003;
        public static final int accessibility_custom_action_11 = 0x7f060004;
        public static final int accessibility_custom_action_12 = 0x7f060005;
        public static final int accessibility_custom_action_13 = 0x7f060006;
        public static final int accessibility_custom_action_14 = 0x7f060007;
        public static final int accessibility_custom_action_15 = 0x7f060008;
        public static final int accessibility_custom_action_16 = 0x7f060009;
        public static final int accessibility_custom_action_17 = 0x7f06000a;
        public static final int accessibility_custom_action_18 = 0x7f06000b;
        public static final int accessibility_custom_action_19 = 0x7f06000c;
        public static final int accessibility_custom_action_2 = 0x7f06000d;
        public static final int accessibility_custom_action_20 = 0x7f06000e;
        public static final int accessibility_custom_action_21 = 0x7f06000f;
        public static final int accessibility_custom_action_22 = 0x7f060010;
        public static final int accessibility_custom_action_23 = 0x7f060011;
        public static final int accessibility_custom_action_24 = 0x7f060012;
        public static final int accessibility_custom_action_25 = 0x7f060013;
        public static final int accessibility_custom_action_26 = 0x7f060014;
        public static final int accessibility_custom_action_27 = 0x7f060015;
        public static final int accessibility_custom_action_28 = 0x7f060016;
        public static final int accessibility_custom_action_29 = 0x7f060017;
        public static final int accessibility_custom_action_3 = 0x7f060018;
        public static final int accessibility_custom_action_30 = 0x7f060019;
        public static final int accessibility_custom_action_31 = 0x7f06001a;
        public static final int accessibility_custom_action_4 = 0x7f06001b;
        public static final int accessibility_custom_action_5 = 0x7f06001c;
        public static final int accessibility_custom_action_6 = 0x7f06001d;
        public static final int accessibility_custom_action_7 = 0x7f06001e;
        public static final int accessibility_custom_action_8 = 0x7f06001f;
        public static final int accessibility_custom_action_9 = 0x7f060020;
        public static final int action_container = 0x7f060021;
        public static final int action_divider = 0x7f060022;
        public static final int action_image = 0x7f060023;
        public static final int action_text = 0x7f060024;
        public static final int actions = 0x7f060025;
        public static final int async = 0x7f060026;
        public static final int blocking = 0x7f060027;
        public static final int chronometer = 0x7f060028;
        public static final int dialog_button = 0x7f060029;
        public static final int edit_text_id = 0x7f06002a;
        public static final int forever = 0x7f06002b;
        public static final int hide_ime_id = 0x7f06002c;
        public static final int icon = 0x7f06002d;
        public static final int icon_group = 0x7f06002e;
        public static final int info = 0x7f06002f;
        public static final int italic = 0x7f060030;
        public static final int line1 = 0x7f060031;
        public static final int line3 = 0x7f060032;
        public static final int normal = 0x7f060033;
        public static final int notification_background = 0x7f060034;
        public static final int notification_main_column = 0x7f060035;
        public static final int notification_main_column_container = 0x7f060036;
        public static final int right_icon = 0x7f060037;
        public static final int right_side = 0x7f060038;
        public static final int tag_accessibility_actions = 0x7f060039;
        public static final int tag_accessibility_clickable_spans = 0x7f06003a;
        public static final int tag_accessibility_heading = 0x7f06003b;
        public static final int tag_accessibility_pane_title = 0x7f06003c;
        public static final int tag_on_apply_window_listener = 0x7f06003d;
        public static final int tag_on_receive_content_listener = 0x7f06003e;
        public static final int tag_on_receive_content_mime_types = 0x7f06003f;
        public static final int tag_screen_reader_focusable = 0x7f060040;
        public static final int tag_state_description = 0x7f060041;
        public static final int tag_transition_group = 0x7f060042;
        public static final int tag_unhandled_key_event_manager = 0x7f060043;
        public static final int tag_unhandled_key_listeners = 0x7f060044;
        public static final int tag_window_insets_animation_callback = 0x7f060045;
        public static final int text = 0x7f060046;
        public static final int text2 = 0x7f060047;
        public static final int time = 0x7f060048;
        public static final int title = 0x7f060049;
        public static final int view_tree_disjoint_parent = 0x7f06004a;
        public static final int view_tree_lifecycle_owner = 0x7f06004b;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f090000;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f0a0000;
        public static final int app_name = 0x7f0a0001;
        public static final int lib_autorun_keepalive_notification_channel = 0x7f0a0009;
        public static final int lib_autorun_keepalive_notification_text = 0x7f0a000a;
        public static final int lib_autorun_keepalive_notification_title = 0x7f0a000b;
        public static final int lib_autorun_notification_channel_backup = 0x7f0a000c;
        public static final int lib_autorun_notification_title_backup = 0x7f0a000e;
        public static final int lib_autorun_runtime_notification_channel = 0x7f0a0010;
        public static final int lib_autorun_runtime_notification_text = 0x7f0a0011;
        public static final int lib_autorun_runtime_notification_title = 0x7f0a0012;
        public static final int lib_autorun_sync_account_type = 0x7f0a0013;
        public static final int lib_autorun_sync_authority = 0x7f0a0014;
        public static final int lib_autorun_sync_label = 0x7f0a0015;
    }

    public static final class xml {
        public static final int authenticator = 0x7f0d0000;
        public static final int sync_adapter = 0x7f0d0001;
    }
}
